[package]
name = "rust-image-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magick_rust = "0.19.1"
imageproc = "0.23.0"
rusttype = "0.9.3"
image = "0.24.7"